# Generated by Django 2.0 on 2018-02-02 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi_entry',
            name='author',
        ),
    ]
