# Generated by Django 2.0 on 2018-02-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0005_kpi_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='group',
            field=models.CharField(choices=[('RD', 'red'), ('GR', 'green'), ('BL', 'blue')], default='BL', max_length=2),
        ),
    ]
