# Generated by Django 2.0 on 2018-02-04 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0006_auto_20180203_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='date_time',
            new_name='datetime_logged',
        ),
    ]
