# Generated by Django 2.0 on 2018-02-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0007_auto_20180204_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='periodicity',
            field=models.CharField(choices=[('DY', 'Daily'), ('YR', 'Yearly'), ('WK', 'Weekly'), ('MH', 'Monthly')], default='DY', max_length=2),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='group',
            field=models.CharField(choices=[('RD', 'Red'), ('GR', 'Green'), ('BL', 'Blue')], default='BL', max_length=2),
        ),
    ]
