# Generated by Django 2.0 on 2018-02-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0008_auto_20180204_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='periodicity',
            field=models.CharField(choices=[('WK', 'Weekly'), ('YR', 'Yearly'), ('DY', 'Daily'), ('MH', 'Monthly')], default='DY', max_length=2),
        ),
    ]
