# Generated by Django 2.0 on 2018-02-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0019_auto_20180204_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='periodicity',
            field=models.CharField(choices=[('DY', 'Daily'), ('MH', 'Monthly'), ('YR', 'Yearly'), ('WK', 'Weekly')], default='DY', max_length=2),
        ),
    ]
