# Generated by Django 2.0 on 2018-02-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0020_auto_20180204_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='periodicity',
            field=models.CharField(choices=[('YR', 'Yearly'), ('DY', 'Daily'), ('MH', 'Monthly'), ('WK', 'Weekly')], default='DY', max_length=2),
        ),
    ]
