# Generated by Django 2.0 on 2018-02-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0021_auto_20180205_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='periodicity',
            field=models.CharField(choices=[('YR', 'Yearly'), ('MH', 'Monthly'), ('WK', 'Weekly'), ('DY', 'Daily')], default='DY', max_length=2),
        ),
    ]
