# Generated by Django 2.0 on 2018-02-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0025_auto_20180207_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='periodicity',
            field=models.CharField(choices=[('DY', 'Daily'), ('YR', 'Yearly'), ('MH', 'Monthly'), ('WK', 'Weekly')], default='DY', max_length=2),
        ),
    ]
